"""Local 869 MHz radio support: frame dialects, payload protocol and gateway link.

This package has no Home Assistant dependency.
"""

from __future__ import annotations

from .dialect import (
    DIALECT_A,
    DIALECT_B,
    DIALECTS,
    Dialect,
    Frame,
    build_ack,
    build_frame,
    decode,
    detect_dialect,
    encode,
    frame_total_length,
)
from .link import (
    AckResult,
    GatewayInfo,
    RadioLink,
    RadioLinkError,
    ReceivedFrame,
    UnsupportedDialectError,
)
from .protocol import (
    MODE_AUTO,
    MODE_MANUAL,
    MODE_NAMES,
    MODE_OFF,
    MODE_OVERRIDE,
    EnergyRecord,
    IdentityRecord,
    PowerRecord,
    PowerRequest,
    ProgramRecord,
    StatusRecord,
    Unsolicited,
    classify_unsolicited,
    decode_energy,
    decode_identity,
    decode_power_record,
    decode_power_request,
    decode_program,
    decode_status,
)
from .survey import RawBurst, SurveyReport, analyse, redact

__all__ = [
    "DIALECTS",
    "DIALECT_A",
    "DIALECT_B",
    "MODE_AUTO",
    "MODE_MANUAL",
    "MODE_NAMES",
    "MODE_OFF",
    "MODE_OVERRIDE",
    "AckResult",
    "Dialect",
    "EnergyRecord",
    "Frame",
    "GatewayInfo",
    "IdentityRecord",
    "PowerRecord",
    "PowerRequest",
    "ProgramRecord",
    "RadioLink",
    "RadioLinkError",
    "RawBurst",
    "ReceivedFrame",
    "StatusRecord",
    "SurveyReport",
    "Unsolicited",
    "UnsupportedDialectError",
    "analyse",
    "build_ack",
    "build_frame",
    "classify_unsolicited",
    "decode",
    "decode_energy",
    "decode_identity",
    "decode_power_record",
    "decode_power_request",
    "decode_program",
    "decode_status",
    "detect_dialect",
    "encode",
    "frame_total_length",
    "redact",
]
