"""Domain-layer primitives for TermoWeb integration."""

from .commands import (
    AccumulatorCommand,
    BaseCommand,
    SetExtraOptions,
    SetMode,
    SetPresetTemps,
    SetProgram,
    SetSetpoint,
    SetUnits,
    StartBoost,
    StopBoost,
)
from .ids import NodeId, NodeType, normalize_node_type
from .inventory import InstallationInventory, NodeInventory
from .state import (
    AccumulatorState,
    DomainState,
    DomainStateStore,
    GatewayConnectionState,
    HeaterState,
    NodeDelta,
    NodeSamplesDelta,
    NodeSettingsDelta,
    NodeStatusDelta,
    PowerMonitorState,
    ThermostatState,
    apply_payload_to_state,
    build_state_from_payload,
    canonicalize_settings_payload,
    clone_gateway_connection_state,
    clone_state,
    state_to_dict,
)
from .view import DomainStateView

__all__ = [
    "AccumulatorCommand",
    "AccumulatorState",
    "BaseCommand",
    "DomainState",
    "DomainStateStore",
    "DomainStateView",
    "GatewayConnectionState",
    "HeaterState",
    "InstallationInventory",
    "NodeDelta",
    "NodeId",
    "NodeInventory",
    "NodeSamplesDelta",
    "NodeSettingsDelta",
    "NodeStatusDelta",
    "NodeType",
    "PowerMonitorState",
    "SetExtraOptions",
    "SetMode",
    "SetPresetTemps",
    "SetProgram",
    "SetSetpoint",
    "SetUnits",
    "StartBoost",
    "StopBoost",
    "ThermostatState",
    "apply_payload_to_state",
    "build_state_from_payload",
    "canonicalize_settings_payload",
    "clone_gateway_connection_state",
    "clone_state",
    "normalize_node_type",
    "state_to_dict",
]
